services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: courier
      ME_CONFIG_BASICAUTH_PASSWORD: courier-password
      ME_CONFIG_MONGODB_ADMINUSERNAME: courier
      ME_CONFIG_MONGODB_ADMINPASSWORD: courier-password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - courier-network
  
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: courier
      MONGO_INITDB_ROOT_PASSWORD: courier-password
      MONGO_INITDB_DATABASE: courier-db
    volumes:
      - mongodb_data:/data/db
    networks:
      - courier-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - courier-network

  courier-service:
    build: .
    container_name: courier-service
    ports:
      - "8081:8080"
    environment:
      MONGO_USERNAME: courier
      MONGO_PASSWORD: courier-password
      MONGO_DATABASE: courier-db
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    networks:
      - courier-network

networks:
  courier-network:
    driver: bridge

volumes:
  mongodb_data: