services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: courier
      ME_CONFIG_BASICAUTH_PASSWORD: courier-password
      ME_CONFIG_MONGODB_ADMINUSERNAME: courier
      ME_CONFIG_MONGODB_ADMINPASSWORD: courier-password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - courier-network
  
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: courier
      MONGO_INITDB_ROOT_PASSWORD: courier-password
      MONGO_INITDB_DATABASE: courier-db
    volumes:
      - mongodb_data:/data/db
    networks:
      - courier-network

  courier-service:
    build: .
    container_name: courier-service
    ports:
      - "8081:8080"
    environment:
      MONGO_USERNAME: courier
      MONGO_PASSWORD: courier-password
      MONGO_DATABASE: courier-db
      MONGO_PORT: 27017
      SPRING_RABBITMQ_HOST: host.docker.internal
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - mongodb
    networks:
      - courier-network
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  courier-network:
    driver: bridge

volumes:
  mongodb_data: